### ISSUE TITLE
Docker way to install RDFIO for Semantic wiki

### ISSUE THREAD

**Issue by sanjar** [rdfio/RDFIO#57]
I am looking for Docker way to install RDFIO for Semantic wiki.
Is there anything available for developers to tryout things on containerized environment?

**Comment by samuell** [comment]
Hi @sanjar , and thanks for the kind words about RDFIO. Glad you like it! :)

Unfortunately, there's nothing created for setting up RDFIO in Docker at the moment.

But maybe one of these resources might help:
- The Vagrant box for RDFIO contains Ansible scripts for setting up RDFIO, which might be repurposed into configuring a Docker image: https://github.com/rdfio/rdfio-vagrantbox
- There are some resources for running Semantic MediaWiki with Docker here: https://www.semantic-mediawiki.org/wiki/Help:Using_Docker
Probably one of these could be adjusted slightly to install RDFIO also. In the best case, maybe it just needs one single line to install RDFIO via the composer PHP package manager.
Otherwise, more info about what is needed to install RDFIO is available in the Ansible script in the RDFIO vagrant box linked above.

Hope this helps!
Best

**Comment by sanjar** [comment]
Thanks @samuell . That really helped.
