### ISSUE TITLE
Cannot access the setup page

### ISSUE THREAD

**Issue by rkamiri** [rdfio/RDFIO#66]
Hi, i've got some issues when setting up rdfio on semantic media wiki version 1.34.1 and semantic mediawiki version 3.1.6.
When accessing the RDFIOAdmin or any special pageit throws a fatal error preventing me to continue the setup process, have you got any idea of why does it append? 
Thanks by advance.

**Comment by samuell** [comment]
Hi @rkamiri , thanks for reporting!

This is most likely due to some known errors, which I have been working to fix, in branch [59-make-work-with-mw-1.34](https://github.com/rdfio/RDFIO/tree/59-make-work-with-mw-1.34). I think I have fixed most of the problems there, but haven't had the time just yet to investigate some remaining testing errors. Thus, using it would be on your own risk at the moment.

Best
Samuel

**Comment by rkamiri** [comment]
Hi @samuell Thanks for the answer, good luck fixing it, i'll try something on my own on the meantime.
